language: php

cache:
  directories:
    - ~/.composer/cache

sudo: false

matrix:
  include:
    - php: 5.5
      dist: trusty
      env: COMPOSER_OPTS=""
    - php: 5.5
      dist: trusty
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 5.6
      dist: xenial
      env: COMPOSER_OPTS=""
    - php: 5.6
      dist: xenial
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.0
      dist: xenial
      env: COMPOSER_OPTS=""
    - php: 7.0
      dist: xenial
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.1
      env: COMPOSER_OPTS=""
    - php: 7.1
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_OPTS=""
    - php: 7.2
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.3
      env: COMPOSER_OPTS=""
    - php: 7.3
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.4
      env: COMPOSER_OPTS=""
    - php: 7.4
      env: COMPOSER_OPTS="--prefer-lowest"

sudo: false

install:
  - if [[ "${TRAVIS_PHP_VERSION}" == "5.5" ]]; then composer require phpunit/phpunit:4.8.36; fi
  - if [[ "${TRAVIS_PHP_VERSION}" == "5.6" ]]; then composer require phpunit/phpunit:5.7.27; fi
  - travis_retry composer update --verbose --no-interaction $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/php-coveralls
