language: php

cache:
  directories:
    - ~/.composer/cache

jobs:
  include:
    - php: 7.3
      env: COMPOSER_OPTS=""
    - php: 7.3
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.4
      env: COMPOSER_OPTS=""
    - php: 7.4
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 8.0
      env: COMPOSER_OPTS=""
    - php: 8.0
      env: COMPOSER_OPTS="--prefer-lowest"

install:
  - travis_retry composer update --verbose --no-interaction $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/php-coveralls
