language: php

php:
  - nightly
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - if [[ "${TRAVIS_PHP_VERSION}" == "5.5" ]]; then composer require phpunit/phpunit:~4.0; fi
  - travis_retry composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/php-coveralls
