language: php

matrix:
  include:
    - php: 7.4snapshot
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      dist: trusty

sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - if [[ "${TRAVIS_PHP_VERSION}" == "5.5" ]]; then composer require phpunit/phpunit:~4.0; fi
  - travis_retry composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/php-coveralls
